Support canonicalizing absolute paths in locks. (#1716)
Although you can still create locks that contain absolute paths from the
local system, Pex now supports canonicalizing such paths for portable
locks with the `--path-mapping` option available when creating and
consuming locks.

The classic example where this is useful is a shared find-links repo
accessed as a network mount somewhere in the user's home directory. A 
portable lock for PEXes that get at least some of their distributions
resolved from such a find-links repo can be created like so:
```
pex3 lock create \
  --find-links $HOME/corp/shares/find-links \
  --path-mapping "\
CORP_FL|$HOME/corp/shares/find-links|\
The local path of the corporate find-links repo network mount.\
"
...
```

The lock file will have all paths beginning with
`$HOME/corp/shares/find-links` substituted with the `${CORP_FL}`
placeholder and the lock will centrally encode all such mappings along
with the description given.

When some other user later uses the `--lock` to create a PEX, they will
be prompted to fill in the `--path-mapping`s if they do not supply them:
```
$ python -mpex --lock lock.json 
,,,
pex.resolve.lockfile.ParseError: The lockfile given in lock.json requires definition of 1 '.path_mappings' entry: CORP_FL
Given no path mappings.
Which left the following path mappings unspecified:
CORP_FL: The local path of the corporate find-links repo network mount.
```

The problem is then corrected by giving the needed path mapping:
```
python -mpex --lock lock.json --path-mapping "CORP_FL|/tmp/find-links"
```
Here, the user mounted the corporate find-links repo in a completely
different place than the lock creator had it mounted at.

Fixes #1413