Lock the mitmproxy resolve to fix at known good. (#1612)
The MarkupSafe dependency had recently released, breaking tests
with a hung process since the test assumes mitmdump will start:
```
$ tox -epy310-integration -- -n0 -vvsk test_requirements_network_configuration
...
Traceback (most recent call last):
  File "/tmp/tmpew1lj8a3/bin/mitmdump", line 8, in <module>
    sys.exit(mitmdump())
...
  File "/tmp/tmpew1lj8a3/lib/python3.10/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/tmp/tmpew1lj8a3/lib/python3.10/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/tmp/tmpew1lj8a3/lib/python3.10/site-packages/markupsafe/__init__.py)
```